//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastinCOFE.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Composition
    {
        public int IDComposition { get; set; }
        public string NameOfIngredient { get; set; }
        public Nullable<int> WeightInGrams { get; set; }
        public Nullable<int> Сalories { get; set; }
    }
}
