//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NastinCOFE.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Check = new HashSet<Check>();
        }
    
        public int IDProduct { get; set; }
        public string NameOfProduct { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<double> Sale { get; set; }
        public Nullable<int> IDTypeOfProduct { get; set; }
        public string Imagen { get; set; }
    
        public virtual TypeOfProduct TypeOfProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Check> Check { get; set; }
    }
}
